# Generated by Django 4.1.5 on 2023-01-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menter',
            new_name='Mentor',
        ),
    ]
